name: CI
on:
  pull_request:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run checks
        run: nix develop --command bash -c "dev check"
      - name: Run coverage
        run: nix develop --command bash -c "elm-coverage -r codecov"
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ./.coverage
          token: ${{ secrets.CODECOV_TOKEN }}
